CREATE DATABASE notebooks;

CREATE IF NOT EXISTS TABLE note (id INT AUTO_INCREMENT PRIMARY KEY, content VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);

CREATE IF NOT EXISTS TABLE tag (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);

CREATE TABLE note_tag (
  note_id INT ,tag_id INT , PRIMARY KEY (note_id, tag_id)
 , FOREIGN KEY (note_id) REFERENCES note (id) ON DELETE CASCADE
 , FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE
);